version: '3'

services:

  core:
    build: ./core
    container_name: alignak-core
    volumes:
      - ./data/log:/usr/local/var/log/alignak

  db:
    image: mongo
    container_name: alignak-db
    volumes:
      - ./data/db:/data/db

  backend:
    build: ./backend
    container_name: alignak-backend
    ports:
      - 5000:5000
    depends_on:
      - db

  webui:
    build: ./webui
    container_name: alignak-webui
    ports:
      - 5001:5001
    depends_on:
      - backend
