version: '3'

services:

  core:
    build: ./core
    volumes:
      - ./data/etc:/usr/local/etc/alignak/
      - ./data/log:/usr/local/var/log/alignak
    ports:
      - 7768:7768

  db:
    image: mongo
    volumes:
      - ./data/db:/data/db

  backend:
    build: ./backend
    ports:
      - 5000:5000
    depends_on:
      - db

  webui:
    build: ./webui
    ports:
      - 5001:5001
    depends_on:
      - backend
